baseURL = "https://ribanez.com.ar/"
languageCode = "en-us"
title = "Rodrigo Ibañez"
theme = "book"
googleAnalytics = "UA-36636133-1"
disqusShortname = "ribanez-com-ar"


[menu]
[[menu.after]]
  name = "Github"
  url = "https://github.com/rsibanez89"
  weight = 10

[[menu.after]]
  name = "Linkedin"
  url = "https://github.com/rsibanez89"
  weight = 20


[params]
  favicon = "favicon.ico"
  description = "Rodrigo Ibanez's personal website."
  linkedin = "https://www.linkedin.com/in/rsibanez89/"
  BookSection = '*'
  BookMenuBundle = '/menu'


[deployment]
[[deployment.targets]]
name = "ribanez"
URL = "s3://ribanez?region=us-east-2"